version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: usdc_postgres
    restart: always
    environment:
      POSTGRES_USER: usdc_user
      POSTGRES_PASSWORD: usdc_password
      POSTGRES_DB: usdc_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: usdc_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      args:
        ENV: development # Change to 'production' for production
    container_name: usdc_analyzer
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["npm", "run", "start:prod"]

volumes:
  postgres_data:
  redis_data: