
services:
  postgres:
    image: postgres:15
    container_name: usdc_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: avalanche_usdc_analyser
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: usdc_redis
    restart: always
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379 
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      args:
        ENV: development # Change to 'production' for production
    container_name: usdc_analyzer
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["npm", "run", "start:prod"]

volumes:
  postgres_data:
  redis_data: